# -*- coding: utf-8 -*-
"""sonoba_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10XKabMpuzaRSp-DdmdXnVkBEBlNtjTyD
"""

import matplotlib.pyplot as plt
import math
import numpy as np

def th(theta1,theta2,dt,nT):
  dth=(theta2-theta1)*dt
  ret=[]
  for i in range(int((theta2-theta1)/dth)):
    ret.append(theta1+i*dth)
  for i in range(int((theta2-theta1)//dth)):
    ret.append(theta2-i*dth)
  ret*=nT
  return ret

def dotphi(A,B,theta):
  return (A-B*np.cos(theta))/(np.sin(theta))**2

def phi(A,B,theta1,theta2,dt,nT):
  dp=list(map(lambda x:dotphi(A,B,x),th(theta1,theta2,dt,nT)))
  p=[]
  p.append(0)
  dth=(theta2-theta1)/dt
  for i in range(len(dp)):
    p.append(p[i]+dp[i]*dt)
  return p

def calc_graph(A,B,theta1,theta2,T,nT):
  dt=1/T
  theta=th(theta1,theta2,dt,nT)
  p=phi(A,B,theta1,theta2,dt,nT)
  x=[]
  y=[]
  for i in range(len(theta)):
    x.append(np.sin(theta[i])*np.cos(p[i]))
    y.append(np.sin(theta[i])*np.sin(p[i]))
  plt.plot(x,y,color='black')
  plt.gca().set_aspect('equal')
  print(len(theta))
  plt.show()

calc_graph(2,-3,np.pi/3,np.pi*6/7,1000,3)